#######################
# Config: Development #
#######################
# (production settings go in _config.build.yml)

name: Decide the Future
sharetitle: Theyâ€™re deciding the future of the Internet right now
url: http://www.decidethefuture.org
description: Find out where these politicians stand on your freedom
timezone: America/Los_Angeles
googleanalytics: UA-26576645-28
author:
  - googleid: 102356128596404327231
  - twitterid: 382376904
  - twitter: fightfortheftr

exclude: [
  'img', 'css', 'fonts', '**.haml',
  '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico',
]

###########
# Content #
###########

future: true
show_drafts: true
permalink: /:title/ # See Jekyll documentation for permalink styles

#############
# Compiling #
#############

highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes
#    - autolink
#    - smart
